### ISSUE TITLE
Error on use in models

### ISSUE THREAD

**Issue by abalad** [smartprocure/sails-nested-blueprint#29] opened 2019-05-03 01:03 UTC
```bash

error: Failed to lift app: Error: Duplicate filename detected: `include-all` attempted to load two files named `deliverycontroller.js` (case-insensitive).
    at E:\Projetos\Speeder\Resources\WebService\node_modules\include-all\lib\help-build-dictionary.js:119:17
    at E:\Projetos\Speeder\Resources\WebService\node_modules\@sailshq\lodash\lib\index.js:3253:15
    at baseForOwn (E:\Projetos\Speeder\Resources\WebService\node_modules\@sailshq\lodash\lib\index.js:2223:14)
    at E:\Projetos\Speeder\Resources\WebService\node_modules\@sailshq\lodash\lib\index.js:3223:18
    at Function.<anonymous> (E:\Projetos\Speeder\Resources\WebService\node_modules\@sailshq\lodash\lib\index.js:3526:13)
    at helpBuildDictionary (E:\Projetos\Speeder\Resources\WebService\node_modules\include-all\lib\help-build-dictionary.js:54:7)
    at Function.module.exports.optional (E:\Projetos\Speeder\Resources\WebService\node_modules\include-all\index.js:67:10)
    at loadActionModules (E:\Projetos\Speeder\Resources\WebService\node_modules\sails\lib\app\private\controller\load-action-modules.js:27:14)
    at async.auto.controller (E:\Projetos\Speeder\Resources\WebService\node_modules\sails\lib\app\load.js:101:9)
    at runTask (E:\Projetos\Speeder\Resources\WebService\node_modules\async\dist\async.js:1619:13)
    at E:\Projetos\Speeder\Resources\WebService\node_modules\async\dist\async.js:1559:13
    at processQueue (E:\Projetos\Speeder\Resources\WebService\node_modules\async\dist\async.js:1569:13)
    at taskComplete (E:\Projetos\Speeder\Resources\WebService\node_modules\async\dist\async.js:1588:9)
    at E:\Projetos\Speeder\Resources\WebService\node_modules\async\dist\async.js:1612:17
    at E:\Projetos\Speeder\Resources\WebService\node_modules\async\dist\async.js:906:16
    at E:\Projetos\Speeder\Resources\WebService\node_modules\sails\lib\app\load.js:191:14

```

![image](https://user-images.githubusercontent.com/5459282/57115554-06b1a100-6d26-11e9-82eb-de2beec3f286.png)

![image](https://user-images.githubusercontent.com/5459282/57115558-129d6300-6d26-11e9-8bcf-33286b9ce53a.png)

**Comment by daedalus28** [comment] 2019-05-03 05:47
Hi @abalad - the error you're seeing seems to be about the same file being loaded twice. I don't think this has anything to do with `sails-nested-blueprint`. If you can consistently reproduce this on a fresh repo we can look into, but it is being used successfully in production now.

With that said, as a team, we have moved on to `feathers` instead of `sails` as it fits our needs much better. While we still have a major production application actively using this library, we are planning to begin a rewrite of it with feathers soon. When we do, we'll likely deprecate this repo unless someone from the community would like to take over maintenance here.

**Comment by daedalus28** [comment] 2019-05-03 05:49
I'm closing this issue since it doesn't seem relevant, but feel free to reopen if you are able to consistently reproduce on a fresh sails app.

**Closed as completed by daedalus28** 2019-05-03 05:49 UTC
